### ISSUE TITLE
Automatically link Github issue/PR when issue/PR numbered is typed

### ISSUE THREAD

**Issue by Darylgolden** [diogoscf/github-lines#15]
It would be helpful, for example if I type a message with a issue/PR number like #5, that the bot sends a link to that issue/PR.

**Comment by onedr0p** [comment]
#5 would be a reference to what thou? How would the bot know what repo to look for that PR/issue number?

**Comment by diogoscf** [comment]
GitHub automatically collapses links to just the number if it's the same repo, I'm guessing they meant a link like `https://github.com/diogoscf/github-lines/issues/5`

**Comment by Darylgolden** [comment]
You could have the user specify a default repo, and have the bot link to that.
