### ISSUE TITLE
Update message when original message is edited

### ISSUE THREAD

**Issue by EpicEricEE** [diogoscf/github-lines#16]
When the link in the original message is edited, the bot's message should be updated as well to include the newly requested lines.

**Comment by onedr0p** [comment]
I am not sure how useful this would be. Usually chat is moving along and people don't go back and look at the message Github Lines creates and instead they look at the link/source. 

Plus you are talking about a service that watches all the link the bot creates and checks for updates. I don't think this is feasible.

**Comment by diogoscf** [comment]
This seems complicated and unnecessary
