### ISSUE TITLE
support discord threads

### ISSUE THREAD

**Issue by keturn** [diogoscf/github-lines#24]
Discord now has [discussion threads](https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ).

Github Lines is either not receiving events for messages in threads, or failing to post its response in thread.

Things I have tried that did not help:
* Granted the [Public Threads](https://support.discord.com/hc/en-us/articles/4404809613847#h_01FBAAVWPHBY1T60KR42DK9HMY) permission to the GitHub Lines role.
* mentioned GitHub Lines (with `@`) in the thread so it appears in the list of users "joined" on that thread.

**Comment by keturn** [comment]
See https://discordjs.guide/popular-topics/threads.html#thread-related-gateway-events

**Comment by diogoscf** [comment]
I suppose this is due to the fact that github lines still runs on discord.js v12 which doesn't support threads afaik. Once it's moved to v13 this should work I believe, although I will check once that's done
