### ISSUE TITLE
Support GitHub gists

### ISSUE THREAD

**Issue by radiantly** [diogoscf/github-lines#7]
On selecting a line in a gist, #filename-linenumber is appended to the url. Maybe the bot can show relevant line(s)?

**Comment by diogoscf** [comment]
This is supported already

**Comment by radiantly** [comment]
Doing a bit of recon, I realised that public gists work as expected, but secret gists do not.

Is there any way this functionality can be made to work with secret gists, or does the API not support it?

**Comment by diogoscf** [comment]
It also works with secret gists?

**Comment by radiantly** [comment]
Hmm, there's something weird going on here, it works with some gists and doesn't work with others ..

**Comment by diogoscf** [comment]
#9
